---
version: '3'
services:

# START SERVICE kafka-rest.base
  kafka-rest:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.kafka-rest.base:5.4.0
    environment: [${CONTECO_DC_KAFKA_REST_ENVIRONMENT}]
    command: [${CONTECO_DC_KAFKA_REST_COMMAND}]
    volumes: [${CONTECO_DC_KAFKA_REST_VOLUMES}]
    ports: [${CONTECO_DC_KAFKA_REST_PORTS}]
    networks: [${CONTECO_DC_KAFKA_REST_NETWORKS}]
    deploy:
      mode: ${CONTECO_DC_KAFKA_REST_DEPLOY_MODE}
      resources:
        limits:
          cpus: '${CONTECO_DC_KAFKA_REST_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_KAFKA_REST_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_KAFKA_REST_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_KAFKA_REST_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_KAFKA_REST_DEPLOY_LABELS}]
# END SERVICE kafka-rest.base

volumes: {${CONTECO_NETWORKLOCAL}_kafka_rest_volume: { external: true }}
networks: {${CONTECO_STACKPREFIX}_overlay: { external: true }}
